let isEnglish = true;

        const translations = {
            en: {
                login: 'Login',
                bookDemo: 'Translation',
                product: 'Product',
                solutions: 'Solutions',
                resources: 'Resources',
                pricing: 'Pricing',
                ultimateTitle: 'The Ultimate AI Customer Service Companion',
                ultimateDescription: 'Embrace AI chatbot technology in a GPT-4-supported communication tool to help your customers, empower your team, and reduce your workload.',
                guideTitle: 'Guide: The Rotar AI Tutorial Hand Book',
                guideDescription: 'Everything you need to know about the first steps in chatbots.',
                readArticle: 'Read Article',
                deliverTitle: 'Deliver a high-quality customer experience',
                deliverDescription: 'Embrace AI chatbot technology in a GPT-4-supported communication tool to help your customers, empower your team, and reduce your workload.',
                workflowTitle: 'Automate your workflow with our integrations',
                workflowDescription: 'Connect Rotar AI with your customer service, sales, marketing, and recruitment tools using our user-friendly API, webhooks, or Zapier integration.',
                boostTitle: 'Boost conversations 96% with AI',
                boostDescription: 'Our AI-powered chatbots and automation tools are here to help.',
                centralizeTitle: 'Centralize Your communication',
                centralizeDescription: 'Easily respond to chats from all of your channels in one overview.',
                liveChatTitle: 'Always accessible with our live chat.',
                liveChatDescription: 'Enhance Communication with Real-Time Live Chat.',
                forgotPassword: 'I´ve forgotten my password',
                resetInstructions: "No worries, we've all been in a melancholy situation like that. To reset your password, go to the login page and click on Forgot Password? Then, enter the email address and follow it.",
                conversationEmployee: 'CONVERSATION EMPLOYEE',
                insightsTitle: 'Gain valuable insights from your audience',
                insightsDescription: 'Statistics provide valuable insights into how customers interact with Rotar AI.',
                watchTutorial: 'Watch Tutorial',
                customerJourney: "Throughout your customer's entire buying journey, Rotar AI allows you to delight them at every step of the way, from their first visit to the final purchase.",
                getStarted: "Get started",
                redefineTitle: "Redefining Conversations and Enhancing User Experience",
                engageTitle: "Engage",
                engageDescription: "Reach out to visitors proactively using personalized chatbot greetings. Turn website visits into sales opportunities.",
                nurtureTitle: "Nurture",
                nurtureDescription: "Lead customers to a sale through recommended purchases and tailored offerings.",
                qualifyTitle: "Qualify",
                qualifyDescription: "Generate and qualify prospects automatically. Transfer high-intent leads to your sales reps in real time to shorten the sales cycle.",
                statusOnline: "Online",
                rotarRobotTitle: "Rotar Robot",
                passwordHelp: "No worries, we've all been in a melancholy situation like that. To reset your password, go to the login page and click on Forgot Password? Then, enter the email address and follow it.",
                solutions: "Solutions",
                services: "Services",
                bookCall: "Book a Call",
                complain: "Complain",
                useTemplates: "Use templates to get started your project",
                ecommerce: "E-commerce",
                education: "Education",
                healthcare: "Health Care",
                financial: "Financial",
                hr: "HR",
                tourism: "Tourism",
                helpText: "Great! Happy to help find the right plan for you. What are you looking to do with Rotar AI?",
                customerGoal: "Get more customers on my website page",
                chatbotMarketing: "Chatbot for Marketing",
                chatbotDescription: "Provide recommendations and process transactions in a chat.",
                tryTemplate: "Try template for free",
                interviewMessage: "You have qualified for the next round of interviews, Alvarez! Please let me know your availability.",
                availabilityResponse: "Any time between 2 to 5 PM tomorrow.",
                chatbotHrTitle: "Chatbot for HR",
                chatbotHrDescription: "Find talent and interact with candidates in an innovative way.",
                tryTemplate: "Try template for free",
                productivityTitle: "Take control of your productivity with a GPT-4 chatbot now",
                transformService: "Transform your Customer Service with Rotar's AI and GPT-4 Powered Chatbot Solution. Try it free now.",
                bookDemo: "Book a Demo",
                company: "Company",
                about: "About Rotar AI",
                pricing: "Pricing",
                demo: "Demo",
                resources: "Resources",
                blog: "Blog",
                events: "Events",
                toolLibrary: "Tool Library",
                legal: "Legal",
                termsOfUse: "Terms of Use",
                privacyPolicy: "Privacy Policy",
                rotarAI: "Rotar AI",
                aboutRotarAI: "We are at the forefront of AI chatbot development, revolutionizing the way businesses engage with their customers.",
                footerRights: "Rotar AI. All Rights Reserved"
            },
            es: {
                login: 'Iniciar sesión',
                bookDemo: 'Traducción',
                product: 'Producto',
                solutions: 'Soluciones',
                resources: 'Recursos',
                pricing: 'Precios',
                ultimateTitle: 'El Compañero Definitivo de Servicio al Cliente con IA',
                ultimateDescription: 'Aprovecha la tecnología de chatbots con IA en una herramienta de comunicación compatible con GPT-4 para ayudar a tus clientes, potenciar tu equipo y reducir tu carga de trabajo.',
                guideTitle: 'Guía: El Manual de Tutorial de Rotar AI',
                guideDescription: 'Todo lo que necesitas saber sobre los primeros pasos en chatbots.',
                readArticle: 'Leer Artículo',
                companies: 'Big companies use Rotar AI for their services',
                aiDriven: 'AI-driven customer services',
                companies: 'Grandes empresas utilizan Rotar AI para sus servicios',
                aiDriven: 'Servicios al cliente impulsados por IA',
                deliverTitle: 'Ofrezca una experiencia de cliente de alta calidad',
                deliverDescription: 'Aproveche la tecnología de chatbot de IA en una herramienta de comunicación compatible con GPT-4 para ayudar a sus clientes, empoderar a su equipo y reducir su carga de trabajo.',
                workflowTitle: 'Automatice su flujo de trabajo con nuestras integraciones',
                workflowDescription: 'Conecte Rotar AI con sus herramientas de servicio al cliente, ventas, marketing y reclutamiento utilizando nuestra API fácil de usar, webhooks o integración con Zapier.',
                boostTitle: 'Aumente las conversaciones un 96% con IA',
                boostDescription: 'Nuestros chatbots y herramientas de automatización impulsados por IA están aquí para ayudar.',
                centralizeTitle: 'Centralice su comunicación',
                centralizeDescription: 'Responda fácilmente a los chats de todos sus canales en una sola vista general.',
                liveChatTitle: 'Siempre accesible con nuestro chat en vivo.',
                liveChatDescription: 'Mejore la comunicación con el chat en vivo en tiempo real.',
                forgotPassword: 'He olvidado mi contraseña',
                resetInstructions: "No te preocupes, todos hemos estado en una situación melancólica como esa. Para restablecer tu contraseña, ve a la página de inicio de sesión y haz clic en ¿Olvidaste tu contraseña? Luego, ingresa tu dirección de correo electrónico y sigue las instrucciones.",
                conversationEmployee: 'EMPLEADO DE CONVERSACIÓN',
                insightsTitle: 'Obtenga información valiosa de su audiencia',
                insightsDescription: 'Las estadísticas brindan información valiosa sobre cómo los clientes interactúan con Rotar AI.',
                watchTutorial: 'Ver Tutorial',
                customerJourney: "A lo largo de todo el proceso de compra de su cliente, Rotar AI le permite deleitarlos en cada paso del camino, desde su primera visita hasta la compra final.",
                getStarted: "Comenzar",
                redefineTitle: "Redefiniendo las Conversaciones y Mejorando la Experiencia del Usuario",
                engageTitle: "Interactuar",
                engageDescription: "Contacta a los visitantes de forma proactiva con saludos personalizados del chatbot. Convierte las visitas en oportunidades de venta.",
                nurtureTitle: "Cultivar",
                nurtureDescription: "Guía a los clientes hacia una compra a través de recomendaciones y ofertas personalizadas.",
                qualifyTitle: "Calificar",
                qualifyDescription: "Genera y califica prospectos automáticamente. Transfiere los clientes potenciales con alta intención a tus representantes de ventas en tiempo real para acortar el ciclo de ventas.",
                statusOnline: "En línea",
                rotarRobotTitle: "Rotar Robot",
                passwordHelp: "No te preocupes, todos hemos estado en una situación melancólica como esa. Para restablecer tu contraseña, ve a la página de inicio de sesión y haz clic en ¿Olvidaste tu contraseña? Luego, ingresa tu dirección de correo electrónico y sigue las instrucciones.",
                solutions: "Soluciones",
                services: "Servicios",
                bookCall: "Reservar una llamada",
                complain: "Quejarse",
                useTemplates: "Usa plantillas para comenzar tu proyecto",
                ecommerce: "Comercio electrónico",
                education: "Educación",
                healthcare: "Atención médica",
                financial: "Finanzas",
                hr: "Recursos humanos",
                tourism: "Turismo",
                helpText: "¡Genial! Feliz de ayudarte a encontrar el plan adecuado para ti. ¿Qué quieres hacer con Rotar AI?",
                customerGoal: "Obtener más clientes en la página de mi sitio web",
                chatbotMarketing: "Chatbot para Marketing",
                chatbotDescription: "Proporciona recomendaciones y procesa transacciones en un chat.",
                tryTemplate: "Probar plantilla gratis",
                interviewMessage: "¡Has calificado para la siguiente ronda de entrevistas, Alvarez! Por favor, dime tu disponibilidad.",
                availabilityResponse: "Cualquier hora entre las 2 y las 5 PM mañana.",
                chatbotHrTitle: "Chatbot para RRHH",
                chatbotHrDescription: "Encuentra talento e interactúa con los candidatos de una manera innovadora.",
                tryTemplate: "Probar plantilla gratis",
                productivityTitle: "Toma el control de tu productividad con un chatbot GPT-4 ahora",
                transformService: "Transforma tu servicio al cliente con la solución de chatbot de Rotar impulsada por GPT-4. Pruébalo gratis ahora.",
                bookDemo: "Reservar una demo",
                company: "Compañía",
                about: "Acerca de Rotar AI",
                pricing: "Precios",
                demo: "Demostración",
                resources: "Recursos",
                blog: "Blog",
                events: "Eventos",
                toolLibrary: "Biblioteca de herramientas",
                legal: "Legal",
                termsOfUse: "Términos de uso",
                privacyPolicy: "Política de privacidad",
                rotarAI: "Rotar AI",
                aboutRotarAI: "Estamos a la vanguardia del desarrollo de chatbots de IA, revolucionando la forma en que las empresas interactúan con sus clientes.",
                footerRights: "Rotar AI. Todos los derechos reservados"
            }
        };

        function changeLanguage() {
            isEnglish = !isEnglish;
            const lang = isEnglish ? 'en' : 'es';

            document.querySelectorAll('[data-i18n]').forEach(el => {
                const key = el.getAttribute('data-i18n');
                if (translations[lang] && translations[lang][key]) {
                    el.textContent = translations[lang][key];
                }
            });
        }